# Site Settings
title: My Resume
url: 'http://francescoborgbonaci.com'
baseurl: '/'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Francesco Elia Borg Bonaci
tagline: Java Backend Developer
pic: profile.jpg
summary: 'My approach to devlopment is that it's not just about writing working code, but about being able to write 
          code that can be understood, used, and extended by any other developer. It is also about taking full responsibility 
          for the code that is written, no matter what happens. I view software development as a craft and I take pride in my 
          approach towards it.'

#sidebar links
#email: hello@webjeda.com
#phone: 012 345 6789
website: francescoborgbonaci.com
linkedin: francescoborgbonaci
github: FrelliBB
#twitter: '@ItsFrelli'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
